# Semana 10, Aula 01 - Simulado de Exploração e Análise de Vendas
**Base real:** Online Retail II — varejo online do Reino Unido (2009–2011)

Percorraremos as RFs do miniprojeto de forma mais enxuta.

### Onde baixar os dados brutos
Vamos realizar o carregamento dessa base de dados, porém, primeiro precisamos baixa-la usando o URL abaixo:
- Kaggle: https://www.kaggle.com/datasets/mashlyn/online-retail-ii-uci

In [1]:
# Passo 1 — Importações 
import pandas as pd
import numpy as np
import re, os, json
import matplotlib.pyplot as plt
import seaborn as sns

## RF01 — Carregar o dataset de vendas

In [2]:
def carregar_dados(caminho="../data/raw/online_retail_II.csv"):
    """Lê o CSV bruto da Online Retail II."""
    df = pd.read_csv(caminho)
    print(f"{len(df)} linhas carregadas.")
    return df

df_bruto = carregar_dados()
df_bruto.head()

1067371 linhas carregadas.

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

## RF02 — Inspecionar e descrever os dados

In [3]:
def inspecionar_dados(df):
    print("INSPECAO INICIAL")
    print(f"Shape: {df.shape}")
    print(f"Colunas: {list(df.columns)}")
    print(f"\nTipos:\n{df.dtypes}")
    print(f"\nNulos por coluna:\n{df.isnull().sum()}")

    return df.describe().round(2)

inspecionar_dados(df_bruto)

INSPECAO INICIAL
Shape: (1067371, 8)
Colunas: ['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

Tipos:
Invoice         object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
Price          float64
Customer ID    float64
Country         object
dtype: object

Nulos por coluna:
Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

         Quantity       Price  Customer ID
count  1067371.00  1067371.00    824364.00
mean         9.94        4.65     15324.64
std        172.71      123.55      1697.46
min     -80995.00   -53594.36     12346.00
25%          1.00        1.25     13975.00
50%          3.00        2.10     15255.00
75%         10.00        4.15     16797.00
max      80995.00    38970.00     18287.00